#theme: jekyll-theme-minimal
#theme: jekyll-theme-architect
#theme: Cayman 
theme: Dinky
#theme: Hacker
#theme: Leap day
#theme: Merlot
#theme: Midnight
#theme: Minima
#theme: Minimal
#theme: Modernist
#theme: Slate
#theme: Tactile
#theme: Time machine
