#theme: jekyll-theme-minimal
theme: Architect
#theme: Cayman#theme: 
#theme: Dinky
#theme: Hacker
#theme: Leap day
#theme: Merlot
#theme: Midnight
#theme: Minima
#theme: Minimal
#theme: Modernist
#theme: Slate
#theme: Tactile
#theme: Time machine
