remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [troymessina.github.io]
description: [code n stuff]
google_analytics: [G-5NX8Z2LXY5]

# theme: jekyll-theme-minimal
# theme: jekyll-theme-architect
# theme: Cayman 
# theme: Dinky
# theme: Hacker
#theme: Leap day
#theme: Merlot
#theme: Midnight
#theme: Minima
#theme: Minimal
#theme: Modernist
#theme: Slate
#theme: Tactile
#theme: Time machine
